config/routes.rb
Rails.application.routes.draw do
  resources :workouts do
    resources :exercises
  end
  root 'workouts#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  belongs_to :workout
end

app/models/workout.rb
class Workout < ApplicationRecord
  has_many :exercises
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def create
    @workout = Workout.find(params[:workout_id])
    @exercise =@workout.exercises.create(exercise_params)
    redirect_to workout_path(@workout)
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :sets, :reps, :workout_id)
  end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
  before_action :find_workout, only: [:show, :edit, :update, :destroy]
  def index
    @workouts = Workout.all.order('created_at DESC')
  end

  def new
    @workout = Workout.new
  end

  def create
    @workout = Workout.new(workout_params)
    if @workout.save
      redirect_to @workout, notice: 'Successfully created'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @workout.update(workout_params)
      redirect_to @workout, notice: 'Successfully updated'
    else
      render :edit      
    end
  end

  def destroy
    @workout.destroy
    redirect_to root_path, notice: 'Successfully destroyed'
  end

  private
  def workout_params
    params.require(:workout).permit(:workout, :mood, :length, :date)
  end

  def find_workout
    @workout = Workout.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/exercises/_exercise.html.haml
%p= exercise.name
= exercise.sets
= exercise.reps

app/views/exercises/_form.html.haml
= form_for ([@workout, @workout.exercises.new]) do |f|
  %p
    = f.label 'Nombre'
    = f.text_field :name
  %p
    = f.label :sets
    = f.number_field :sets
  %p
    = f.label :reps
    = f.number_field :reps
  %p= f.submit

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title WorkoutLog
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render 'layouts/shared/message'
    = yield

app/views/layouts/shared/_message.html.haml
- flash.each do |key, value|
  %div{:class => "alert alert-#{key}"}
    %a.close{"data-dismiss" => "alert", :href => "#"} ×
    %ul
      %li
        = value

app/views/workouts/_form.html.haml
= form_for @workout do |f|
  %p
    = f.label :workout
    = f.text_field :workout
  %p
    = f.label :mood
    = f.text_field :mood
  %p
    = f.label :length
    = f.text_field :length
  %p= f.datetime_select(:date) 
  %p= f.submit

app/views/workouts/edit.html.haml
= render 'form'

app/views/workouts/index.html.haml
= link_to 'New workout', new_workout_path
%p elements
- @workouts.each do |workout|
  %p= link_to workout.date.strftime("%A %B %d"), workout
  %p= workout.workout

app/views/workouts/new.html.haml
= render 'form'

app/views/workouts/show.html.haml
%p= @workout.workout
= link_to 'edit', edit_workout_path(@workout)
= link_to 'delete', workout_path, method: :delete, data: { confirm: 'Are you sure?'}
= render @workout.exercises
= render 'exercises/form'